"""initial migration

Revision ID: 41748b9cb5eb
Revises: 
Create Date: 2025-01-18 12:14:42.414445

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '41748b9cb5eb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('climbing_grade')
    with op.batch_alter_table('route', schema=None) as batch_op:
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
        batch_op.drop_index('idx_route_grade_id')
        batch_op.drop_index('idx_route_gym_id')
        batch_op.create_unique_constraint('unique_route_per_gym', ['route_id', 'gym_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route', schema=None) as batch_op:
        batch_op.drop_constraint('unique_route_per_gym', type_='unique')
        batch_op.create_index('idx_route_gym_id', ['gym_id'], unique=False)
        batch_op.create_index('idx_route_grade_id', ['grade_id'], unique=False)
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))

    op.create_table('climbing_grade',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('grade', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('climbing_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('points', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('difficulty_rank', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='climbing_grade_pkey')
    )
    # ### end Alembic commands ###
